# Generated by Django 3.2.7 on 2022-01-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echango', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
    ]
