# Generated by Django 3.2.7 on 2022-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echango', '0002_lineapedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
