# Generated by Django 3.2.7 on 2022-01-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echango', '0004_remove_lineapedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
