# Generated by Django 3.2.7 on 2022-01-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echango', '0005_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='total',
        ),
    ]
