# Generated by Django 3.2.7 on 2021-09-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
