# Generated by Django 3.2.7 on 2022-01-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuario'},
        ),
    ]
